
using NUnit.Framework;
using MyCode;

namespace MyCode.Tests
{
    [TestFixture]
    public class MyClassNextTests
    {
        
        [Test]
        public void FirstMethod1Test()
        {
            Assert.Fail("autogenerated");
        }
        
        [Test]
        public void SecondMethod1Test()
        {
            Assert.Fail("autogenerated");
        }
        
        [Test]
        public void ThirdMethod1Test()
        {
            Assert.Fail("autogenerated");
        }
        
        [Test]
        public void ThirdMethod2Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}