
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyCode;

namespace MyCode.Tests
{
    [TestClass]
    public class MyClassNextTests
    {
        private MyClassNext _myClassNextUnderTest;
        
        
        
        [TestInitialize]
        public void Initialize()
        {  
            
            
            _myClassNextUnderTest = new MyClassNext();
        }

        
        [TestMethod]
        public void FirstMethod1Test()
        {
            _myClassNextUnderTest.FirstMethod();

            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void SecondMethod1Test()
        {
            _myClassNextUnderTest.SecondMethod();

            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void ThirdMethod1Test()
        {
            int a = 0;

            _myClassNextUnderTest.ThirdMethod(a);

            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void ThirdMethod2Test()
        {
            double a = 0;

            _myClassNextUnderTest.ThirdMethod(a);

            Assert.Fail("autogenerated");
        }
    }
}