
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class AnalyticsEngineTests
    {
        private AnalyticsEngine _analyticsEngineUnderTest;
        
        private int _sampleSize;
        
        [TestInitialize]
        public void Initialize()
        {  
            _sampleSize = 0;
            
            _analyticsEngineUnderTest = new AnalyticsEngine(_sampleSize);
        }

        
        [TestMethod]
        public void RunAnalysis1Test()
        {
            _analyticsEngineUnderTest.RunAnalysis();

            Assert.Fail("autogenerated");
        }
    }
}