
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class CalculatorTests
    {
        private Calculator _calculatorUnderTest;
        
        
        
        [TestInitialize]
        public void Initialize()
        {  
            
            
            _calculatorUnderTest = new Calculator();
        }

        
        [TestMethod]
        public void Add1Test()
        {
            int a = 0;
            int b = 0;

            int actual = _calculatorUnderTest.Add(a, b);

            int expected = 0;
            Assert.AreEqual(expected, actual);
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void Subtract1Test()
        {
            int a = 0;
            int b = 0;

            int actual = _calculatorUnderTest.Subtract(a, b);

            int expected = 0;
            Assert.AreEqual(expected, actual);
            Assert.Fail("autogenerated");
        }
    }
}