
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class ConfigManagerTests
    {
        private ConfigManager _configManagerUnderTest;
        
        
        
        [TestInitialize]
        public void Initialize()
        {  
            
            
            _configManagerUnderTest = new ConfigManager();
        }

        
        [TestMethod]
        public void LoadConfig1Test()
        {
            _configManagerUnderTest.LoadConfig();

            Assert.Fail("autogenerated");
        }
    }
}