
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class EmailSenderTests
    {
        private EmailSender _emailSenderUnderTest;
        
        
        
        [TestInitialize]
        public void Initialize()
        {  
            
            
            _emailSenderUnderTest = new EmailSender();
        }

        
        [TestMethod]
        public void SendEmail1Test()
        {
            string to = "";
            string subject = "";
            string body = "";

            _emailSenderUnderTest.SendEmail(to, subject, body);

            Assert.Fail("autogenerated");
        }
    }
}