
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class EventLoggerTests
    {
        private EventLogger _eventLoggerUnderTest;
        private Mock<ILogger> _loggerMock;
        
        
        [TestInitialize]
        public void Initialize()
        {  
            
            _loggerMock = new Mock<ILogger>();
            _eventLoggerUnderTest = new EventLogger(_loggerMock.Object);
        }

        
        [TestMethod]
        public void LogEvent1Test()
        {
            string eventDescription = "";

            bool actual = _eventLoggerUnderTest.LogEvent(eventDescription);

            bool expected = false;
            Assert.AreEqual(expected, actual);
            Assert.Fail("autogenerated");
        }
    }
}