
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class FileHandlerTests
    {
        private FileHandler _fileHandlerUnderTest;
        
        private string _filePath;
        private int _bufferSize;
        
        [TestInitialize]
        public void Initialize()
        {  
            _filePath = "";
            _bufferSize = 0;
            
            _fileHandlerUnderTest = new FileHandler(_filePath, _bufferSize);
        }

        
        [TestMethod]
        public void ReadFile1Test()
        {
            _fileHandlerUnderTest.ReadFile();

            Assert.Fail("autogenerated");
        }
    }
}