
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class LoggerTests
    {
        private Logger _loggerUnderTest;
        
        
        
        [TestInitialize]
        public void Initialize()
        {  
            
            
            _loggerUnderTest = new Logger();
        }

        
        [TestMethod]
        public void Log1Test()
        {
            string message = "";

            _loggerUnderTest.Log(message);

            Assert.Fail("autogenerated");
        }
    }
}