
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class NotificationServiceTests
    {
        private NotificationService _notificationServiceUnderTest;
        private Mock<IEmailSender> _emailSenderMock;
        
        
        [TestInitialize]
        public void Initialize()
        {  
            
            _emailSenderMock = new Mock<IEmailSender>();
            _notificationServiceUnderTest = new NotificationService(_emailSenderMock.Object);
        }

        
        [TestMethod]
        public void Notify1Test()
        {
            string email = "";
            string subject = "";

            _notificationServiceUnderTest.Notify(email, subject);

            Assert.Fail("autogenerated");
        }
    }
}