
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class PaymentProcessorTests
    {
        private PaymentProcessor _paymentProcessorUnderTest;
        
        private bool _useSandbox;
        
        [TestInitialize]
        public void Initialize()
        {  
            _useSandbox = false;
            
            _paymentProcessorUnderTest = new PaymentProcessor(_useSandbox);
        }

        
        [TestMethod]
        public void ProcessPayment1Test()
        {
            int amount = 0;

            _paymentProcessorUnderTest.ProcessPayment(amount);

            Assert.Fail("autogenerated");
        }
    }
}