
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class ReportGeneratorTests
    {
        private ReportGenerator _reportGeneratorUnderTest;
        
        private string _reportName;
        
        [TestInitialize]
        public void Initialize()
        {  
            _reportName = "";
            
            _reportGeneratorUnderTest = new ReportGenerator(_reportName);
        }

        
        [TestMethod]
        public void GenerateReport1Test()
        {
            double actual = _reportGeneratorUnderTest.GenerateReport();

            double expected = 0;
            Assert.AreEqual(expected, actual);
            Assert.Fail("autogenerated");
        }
    }
}