
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class SchedulerTests
    {
        private Scheduler _schedulerUnderTest;
        
        private int _interval;
        
        [TestInitialize]
        public void Initialize()
        {  
            _interval = 0;
            
            _schedulerUnderTest = new Scheduler(_interval);
        }

        
        [TestMethod]
        public void ScheduleJob1Test()
        {
            int jobId = 0;

            string actual = _schedulerUnderTest.ScheduleJob(jobId);

            string expected = "";
            Assert.AreEqual(expected, actual);
            Assert.Fail("autogenerated");
        }
    }
}