
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class SecurityManagerTests
    {
        private SecurityManager _securityManagerUnderTest;
        
        private bool _enableEncryption;
        private string _secretKey;
        
        [TestInitialize]
        public void Initialize()
        {  
            _enableEncryption = false;
            _secretKey = "";
            
            _securityManagerUnderTest = new SecurityManager(_enableEncryption, _secretKey);
        }

        
        [TestMethod]
        public void Authenticate1Test()
        {
            string username = "";
            string password = "";

            _securityManagerUnderTest.Authenticate(username, password);

            Assert.Fail("autogenerated");
        }
    }
}