
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class ServiceATests
    {
        private ServiceA _serviceAUnderTest;
        private Mock<IService> _serviceMock;
        
        
        [TestInitialize]
        public void Initialize()
        {  
            
            _serviceMock = new Mock<IService>();
            _serviceAUnderTest = new ServiceA(_serviceMock.Object);
        }

        
        [TestMethod]
        public void ExecuteService1Test()
        {
            int value = 0;

            _serviceAUnderTest.ExecuteService(value);

            Assert.Fail("autogenerated");
        }
    }
}