
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class SessionManagerTests
    {
        private SessionManager _sessionManagerUnderTest;
        
        private string _sessionId;
        
        [TestInitialize]
        public void Initialize()
        {  
            _sessionId = "";
            
            _sessionManagerUnderTest = new SessionManager(_sessionId);
        }

        
        [TestMethod]
        public void StartSession1Test()
        {
            _sessionManagerUnderTest.StartSession();

            Assert.Fail("autogenerated");
        }
    }
}