
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class UserProfileTests
    {
        private UserProfile _userProfileUnderTest;
        
        private string _username;
        private int _age;
        
        [TestInitialize]
        public void Initialize()
        {  
            _username = "";
            _age = 0;
            
            _userProfileUnderTest = new UserProfile(_username, _age);
        }

        
        [TestMethod]
        public void DisplayProfile1Test()
        {
            _userProfileUnderTest.DisplayProfile();

            Assert.Fail("autogenerated");
        }
    }
}