
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using MyApp;

namespace MyApp.Tests
{
    [TestClass]
    public class UserManagerTests
    {
        private UserManager _userManagerUnderTest;
        private Mock<IDataRepository> _repositoryMock;
        
        
        [TestInitialize]
        public void Initialize()
        {  
            
            _repositoryMock = new Mock<IDataRepository>();
            _userManagerUnderTest = new UserManager(_repositoryMock.Object);
        }

        
        [TestMethod]
        public void CreateUser1Test()
        {
            string username = "";

            _userManagerUnderTest.CreateUser(username);

            Assert.Fail("autogenerated");
        }
    }
}